//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace JNCC.PublicWebsite.Core.Models
{
	/// <summary>Articulate Author</summary>
	[PublishedContentModel("ArticulateAuthor")]
	public partial class ArticulateAuthor : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ArticulateAuthor";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ArticulateAuthor(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ArticulateAuthor, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Author Bio: Description of the author
		///</summary>
		[ImplementPropertyType("authorBio")]
		public string AuthorBio
		{
			get { return this.GetPropertyValue<string>("authorBio"); }
		}

		///<summary>
		/// Author Image
		///</summary>
		[ImplementPropertyType("authorImage")]
		public Umbraco.Web.Models.ImageCropDataSet AuthorImage
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("authorImage"); }
		}

		///<summary>
		/// Author Url: A url to link to the author's website
		///</summary>
		[ImplementPropertyType("authorUrl")]
		public string AuthorUrl
		{
			get { return this.GetPropertyValue<string>("authorUrl"); }
		}
	}
}
