//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace JNCC.PublicWebsite.Core.Models
{
	/// <summary>Home Page</summary>
	[PublishedContentModel("homePage")]
	public partial class HomePage : PublishedContentModel, INavigationSettingsComposition, ISeoComposition
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content: A content area useful display for displaying legal & copyright information within the footer of the page.
		///</summary>
		[ImplementPropertyType("footerContent")]
		public IHtmlString FooterContent
		{
			get { return this.GetPropertyValue<IHtmlString>("footerContent"); }
		}

		///<summary>
		/// Social Media Links: Links to various social media channels.
		///</summary>
		[ImplementPropertyType("footerSocialMediaLinks")]
		public Umbraco.Web.Models.RelatedLinks FooterSocialMediaLinks
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("footerSocialMediaLinks"); }
		}

		///<summary>
		/// Uncategorised Links: Uncategorised links that appear at the very bottom of the footer.
		///</summary>
		[ImplementPropertyType("footerUncategorisedLinks")]
		public IEnumerable<RJP.MultiUrlPicker.Models.Link> FooterUncategorisedLinks
		{
			get { return this.GetPropertyValue<IEnumerable<RJP.MultiUrlPicker.Models.Link>>("footerUncategorisedLinks"); }
		}

		///<summary>
		/// Hero Carousel: A collection of carousel slides to be displayed at the top of the page.
		///</summary>
		[ImplementPropertyType("heroCarousel")]
		public IEnumerable<IPublishedContent> HeroCarousel
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("heroCarousel"); }
		}

		///<summary>
		/// Hide Children from Navigation: Hides any child pages from the main navigation.
		///</summary>
		[ImplementPropertyType("umbracoNavi")]
		public bool UmbracoNavi
		{
			get { return JNCC.PublicWebsite.Core.Models.NavigationSettingsComposition.GetUmbracoNavi(this); }
		}

		///<summary>
		/// Hide from Navigation: Hides the page from the main navigation.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return JNCC.PublicWebsite.Core.Models.NavigationSettingsComposition.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// SEO Settings
		///</summary>
		[ImplementPropertyType("seoSettings")]
		public SEOChecker.MVC.MetaData SeoSettings
		{
			get { return JNCC.PublicWebsite.Core.Models.SeoComposition.GetSeoSettings(this); }
		}
	}
}
