//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace JNCC.PublicWebsite.Core.Models
{
	// Mixin content Type 1149 with alias "pageHeroCarouselComposition"
	/// <summary>Page Hero Carousel Composition</summary>
	public partial interface IPageHeroCarouselComposition : IPublishedContent
	{
		/// <summary>Headline</summary>
		string Headline { get; }

		/// <summary>Hero Content</summary>
		IHtmlString HeroContent { get; }

		/// <summary>Hero Images</summary>
		IEnumerable<IPublishedContent> HeroImages { get; }
	}

	/// <summary>Page Hero Carousel Composition</summary>
	[PublishedContentModel("pageHeroCarouselComposition")]
	public partial class PageHeroCarouselComposition : PublishedContentModel, IPageHeroCarouselComposition
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageHeroCarouselComposition";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageHeroCarouselComposition(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageHeroCarouselComposition, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Headline: A headline which appears within the Hero Carousel.
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return GetHeadline(this); }
		}

		/// <summary>Static getter for Headline</summary>
		public static string GetHeadline(IPageHeroCarouselComposition that) { return that.GetPropertyValue<string>("headline"); }

		///<summary>
		/// Hero Content: A brief paragraph to be displayed within the hero carousel.
		///</summary>
		[ImplementPropertyType("heroContent")]
		public IHtmlString HeroContent
		{
			get { return GetHeroContent(this); }
		}

		/// <summary>Static getter for Hero Content</summary>
		public static IHtmlString GetHeroContent(IPageHeroCarouselComposition that) { return that.GetPropertyValue<IHtmlString>("heroContent"); }

		///<summary>
		/// Hero Images: Images to be displayed in the hero image carousel
		///</summary>
		[ImplementPropertyType("heroImages")]
		public IEnumerable<IPublishedContent> HeroImages
		{
			get { return GetHeroImages(this); }
		}

		/// <summary>Static getter for Hero Images</summary>
		public static IEnumerable<IPublishedContent> GetHeroImages(IPageHeroCarouselComposition that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("heroImages"); }
	}
}
