//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace JNCC.PublicWebsite.Core.Models
{
	// Mixin content Type 1126 with alias "pageSpecificIncludesComposition"
	/// <summary>Page-Specific Includes Composition</summary>
	public partial interface IPageSpecificIncludesComposition : IPublishedContent
	{
		/// <summary>HTML Lang Ref</summary>
		string HTmllangRef { get; }

		/// <summary>Page-specific BODY Includes</summary>
		string PageSpecificBodyIncludes { get; }

		/// <summary>Page-specific HEAD Includes</summary>
		string PageSpecificHeadIncludes { get; }
	}

	/// <summary>Page-Specific Includes Composition</summary>
	[PublishedContentModel("pageSpecificIncludesComposition")]
	public partial class PageSpecificIncludesComposition : PublishedContentModel, IPageSpecificIncludesComposition
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageSpecificIncludesComposition";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageSpecificIncludesComposition(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageSpecificIncludesComposition, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// HTML Lang Ref: This field should be used when the page is of another language.  When a value is not present in this field, the default value will be "en-GB".
		///</summary>
		[ImplementPropertyType("hTMLLangRef")]
		public string HTmllangRef
		{
			get { return GetHTmllangRef(this); }
		}

		/// <summary>Static getter for HTML Lang Ref</summary>
		public static string GetHTmllangRef(IPageSpecificIncludesComposition that) { return that.GetPropertyValue<string>("hTMLLangRef"); }

		///<summary>
		/// Page-specific BODY Includes: Authored code includes which will only appear on this page and will be rendered at the end of the BODY tag in the HTML.  This is useful for adding tracking code. Styling should not be authored here and should instead be authored in the head.  This should be edited by administrators only.
		///</summary>
		[ImplementPropertyType("pageSpecificBodyIncludes")]
		public string PageSpecificBodyIncludes
		{
			get { return GetPageSpecificBodyIncludes(this); }
		}

		/// <summary>Static getter for Page-specific BODY Includes</summary>
		public static string GetPageSpecificBodyIncludes(IPageSpecificIncludesComposition that) { return that.GetPropertyValue<string>("pageSpecificBodyIncludes"); }

		///<summary>
		/// Page-specific HEAD Includes: Authored code includes which will only appear on this page and will be rendered at the end of the HEAD tag in the HTML.  This is useful for adding tracking code and style elements.  This should be edited by administrators only.
		///</summary>
		[ImplementPropertyType("pageSpecificHeadIncludes")]
		public string PageSpecificHeadIncludes
		{
			get { return GetPageSpecificHeadIncludes(this); }
		}

		/// <summary>Static getter for Page-specific HEAD Includes</summary>
		public static string GetPageSpecificHeadIncludes(IPageSpecificIncludesComposition that) { return that.GetPropertyValue<string>("pageSpecificHeadIncludes"); }
	}
}
