//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace JNCC.PublicWebsite.Core.Models
{
	// Mixin content Type 1112 with alias "relatedItemsComposition"
	/// <summary>Related Items Composition</summary>
	public partial interface IRelatedItemsComposition : IPublishedContent
	{
		/// <summary>Items</summary>
		IEnumerable<IPublishedContent> RelatedItems { get; }
	}

	/// <summary>Related Items Composition</summary>
	[PublishedContentModel("relatedItemsComposition")]
	public partial class RelatedItemsComposition : PublishedContentModel, IRelatedItemsComposition
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "relatedItemsComposition";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public RelatedItemsComposition(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<RelatedItemsComposition, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Items: Provides related items for the current page. These items are manually authored. A maximum of 3 items can be authored.  If no items are provided then the related items section will not be rendered.
		///</summary>
		[ImplementPropertyType("relatedItems")]
		public IEnumerable<IPublishedContent> RelatedItems
		{
			get { return GetRelatedItems(this); }
		}

		/// <summary>Static getter for Items</summary>
		public static IEnumerable<IPublishedContent> GetRelatedItems(IRelatedItemsComposition that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("relatedItems"); }
	}
}
