//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace JNCC.PublicWebsite.Core.Models
{
	// Mixin content Type 1165 with alias "sciencePageCategorisationComposition"
	/// <summary>Science Page Categorisation Composition</summary>
	public partial interface ISciencePageCategorisationComposition : IPublishedContent
	{
		/// <summary>Category Ordering Name</summary>
		string CategoryOrderingName { get; }
	}

	/// <summary>Science Page Categorisation Composition</summary>
	[PublishedContentModel("sciencePageCategorisationComposition")]
	public partial class SciencePageCategorisationComposition : PublishedContentModel, ISciencePageCategorisationComposition
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sciencePageCategorisationComposition";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SciencePageCategorisationComposition(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SciencePageCategorisationComposition, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Category Ordering Name: [Optional] Determines how the page is categorised on a Science Category Page.   If no value is authored then the headline is used followed by the page name.
		///</summary>
		[ImplementPropertyType("categoryOrderingName")]
		public string CategoryOrderingName
		{
			get { return GetCategoryOrderingName(this); }
		}

		/// <summary>Static getter for Category Ordering Name</summary>
		public static string GetCategoryOrderingName(ISciencePageCategorisationComposition that) { return that.GetPropertyValue<string>("categoryOrderingName"); }
	}
}
