//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace JNCC.PublicWebsite.Core.Models
{
	/// <summary>Science Category Sub Section Slider Schema</summary>
	[PublishedContentModel("scienceCategorySubSectionSliderSchema")]
	public partial class ScienceCategorySubSectionSliderSchema : ScienceCategorySectionBaseSchema
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "scienceCategorySubSectionSliderSchema";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ScienceCategorySubSectionSliderSchema(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ScienceCategorySubSectionSliderSchema, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content: Content to display above the image slider.
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return this.GetPropertyValue<IHtmlString>("content"); }
		}

		///<summary>
		/// Show Grey Background: By setting this to "True" all slider items will have a grey background applied. By default no background will be applied.
		///</summary>
		[ImplementPropertyType("showGreyBackground")]
		public bool ShowGreyBackground
		{
			get { return this.GetPropertyValue<bool>("showGreyBackground"); }
		}

		///<summary>
		/// Show Timeline Arrows: By setting this to "True" a timeline arrow will be added between the slider items. By default no timeline arrows will be applied.
		///</summary>
		[ImplementPropertyType("showTimelineArrows")]
		public bool ShowTimelineArrows
		{
			get { return this.GetPropertyValue<bool>("showTimelineArrows"); }
		}

		///<summary>
		/// Slider Items: Section to create the slider items displayed, the order of these items will determine the order the items are displayed in the slider.
		///</summary>
		[ImplementPropertyType("sliderItems")]
		public IEnumerable<IPublishedContent> SliderItems
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("sliderItems"); }
		}
	}
}
