//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace JNCC.PublicWebsite.Core.Models
{
	/// <summary>Staff Profile Page</summary>
	[PublishedContentModel("StaffProfilePage")]
	public partial class StaffProfilePage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "StaffProfilePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StaffProfilePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StaffProfilePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("biographyContent")]
		public IHtmlString BiographyContent
		{
			get { return this.GetPropertyValue<IHtmlString>("biographyContent"); }
		}

		///<summary>
		/// Job Title
		///</summary>
		[ImplementPropertyType("jobTitle")]
		public string JobTitle
		{
			get { return this.GetPropertyValue<string>("jobTitle"); }
		}

		///<summary>
		/// Profile Picture
		///</summary>
		[ImplementPropertyType("profilePicture")]
		public IPublishedContent ProfilePicture
		{
			get { return this.GetPropertyValue<IPublishedContent>("profilePicture"); }
		}

		///<summary>
		/// Profile Tags: Tags to group staff profiles by shared attributes (e.g. location or division)
		///</summary>
		[ImplementPropertyType("profileTags")]
		public IEnumerable<string> ProfileTags
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("profileTags"); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("projectsContent")]
		public IHtmlString ProjectsContent
		{
			get { return this.GetPropertyValue<IHtmlString>("projectsContent"); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("publicationsContent")]
		public IHtmlString PublicationsContent
		{
			get { return this.GetPropertyValue<IHtmlString>("publicationsContent"); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("researchContent")]
		public IHtmlString ResearchContent
		{
			get { return this.GetPropertyValue<IHtmlString>("researchContent"); }
		}
	}
}
